Events Management System Version 2.1/Models/User-Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Events_Management_System_Version_2._1.Models;

// this a bridge table to resolve the event user many to many relationship
namespace Events_Management_System_Version_2._1.Models
{
    public class User_Event
    {
        // attributes 
        public int ID { get; set; }                             // primary key 
        public virtual Event Event { get; set; }                // foreign key from events table
        public virtual ApplicationUser User { get; set; }       // foreign key from aspnetusers 

        // constructor 
        public User_Event()
        {

        }

        public User_Event(Event evnt, ApplicationUser usr)
        {
            this.Event = evnt;
            this.User = usr;
        }
    }
}

Events Management System Version 2.1/Controllers/UserEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Events_Management_System_Version_2._1.Models;

namespace Events_Management_System_Version_2._1.Controllers
{
    public class UserEventController : Controller
    {
        private ApplicationDbContext context;

        // constructor 
        public UserEventController()
        {
            context = new ApplicationDbContext();
        }

        // dispose db context 
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        public ActionResult MyEvents()
        {
            var UE = context.UserEvent.ToList();                    // user events 
            return View(UE);
        }

        public ActionResult SingleQR(int id)
        {
            var user_evnt = context.UserEvent.SingleOrDefault(ue => ue.ID == id);
            return View(user_evnt);
        }

    }
}

Events Management System Version 2.1/Views/UserEvent/MyEvents.cshtml
@model IEnumerable<Events_Management_System_Version_2._1.Models.User_Event>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "MyEvents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!(Model.Any()))
{
    <h5>You are not Enrolled in any events</h5>
}
else
{
    int x = 0;

    <section class="upcoming full-width">
        <h1 class="title">
            My Events
        </h1>
    </section>

    <section class="events full-width">
        <br />  
        <table style="margin: 0 auto; min-height:1000px;">
            @for (int i = 0; i < 5; i++)
            {
                <tr>
                    @for (int j = 0; j < 2; j++)
                    {
                        if (Model.Count() > x && Model.ElementAt(x).User != null && Model.ElementAt(x).Event != null)
                        {
                            if (string.Equals(User.Identity.GetUserId(), Model.ElementAt(x).User.Id))
                            {
                                <td>
									<div class="card" style="width:300px; height:100px; margin:0 auto;">
										<div class="card-body">
											<h4 class="card-title">@Model.ElementAt(x).Event.Title</h4>
											<a href='@Url.Action("SingleQR", "UserEvent",  new { id = Model.ElementAt(x).ID })' class="card-link">View QR-code</a>
										</div>
									</div>
								</td>
                            }
                        }
                        x++;
                    }
                </tr>
            }
        </table>
    </section>
}

Events Management System Version 2.1/Views/UserEvent/SingleQR.cshtml
@model Events_Management_System_Version_2._1.Models.User_Event
@Scripts.Render("~/Content/qrcode.min.js")
@{
    ViewBag.Title = "SingleQR";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="events full-width" style="min-height:1000px">
    <br />
    <div class="card mb-3" style="max-height:50%; max-width:50%; margin:0 auto;">
        <h3 class="card-header">@Model.Event.Title</h3>
        <div id="QR-area" style="margin:0 auto;"></div>
        <div class="card-footer text-muted">
            @Model.Event.Added_Date
        </div>
    </div>
</section>

@section scripts
{
    <script>
        var qrcode = new QRCode(document.getElementById("QR-area"),
		{
            text: "@Model.Event.Code" + "-" +"@Model.User.Id" ,
            width: 300,
            height: 300,
            colorDark : "#000000",
            colorLight: "#ffffff",
            correctLevel : QRCode.CorrectLevel.H
        });
    </script>
}