Events Management System Version 2.1/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Events_Management_System_Version_2._1.Models
{
    public class Event
    {
        //attributes 
        public int ID { get; set; }         //primary key 

        [Required]
        [MaxLength(100)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [MaxLength(300)]
        [Display(Name = "Partial Content")]
        public string partialContent { get; set; }

        [Required]
        [Display(Name = "Full Content")]
        public string fullContent { get; set; }

        [Required]
        [MaxLength(6)]
        [Display(Name = "Event Code")]
        public String Code { get; set; }

        [Display(Name = "Display Image")]
        public string image { get; set; }

        [Display(Name = "Added Date")]
        public DateTime Added_Date { get; set; }
    }
}

Events Management System Version 2.1/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Events_Management_System_Version_2._1.Models;

namespace Events_Management_System_Version_2._1.Controllers
{
    public class EventController : Controller
    {
        // Instance of Database context
        private ApplicationDbContext context;

        // constructor 
        public EventController()
        {
            context = new ApplicationDbContext();
        }

        // dispose db context 
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        [Authorize]
        public ActionResult AllEvents()
        {
            var events = context.Events.ToList();
            return View(events);
        }

        [Authorize]
        public ActionResult Single(int id)
        {
            var evnt = context.Events.SingleOrDefault(e => e.ID == id);
            return View(evnt);
        }

        // action result to enroll a user in an event
        [HttpPost]
        [Authorize]
        public ActionResult Enroll(Event evnt)
        {

            Event ev = context.Events.SingleOrDefault(e => e.ID == evnt.ID);
            ApplicationUser us = context.Users.FirstOrDefault();
            User_Event UE = new User_Event(ev, us);

            context.UserEvent.Add(UE);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Events Management System Version 2.1/Views/Event/AllEvents.cshtml
@model IEnumerable<Events_Management_System_Version_2._1.Models.Event>
@{
    ViewBag.Title = "AllEvents";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (!(Model.Any()))
{
    <h5>No Events Found</h5>
}
else
{

    int x = 0;

    <section class="upcoming full-width">
        <h1 class="title">
            All Events
        </h1>
    </section>

    <section class="events full-width" id="upcoming">
        <br />
        <table style="margin: 0 auto;">
            @for (int i = 0; i < 5; i++)
            {
                <tr>

                    @for (int j = 0; j < 2; j++)
                    {
                        if (Model.Count() > x)
                        {
                            <td>
                                <div class="card text-white bg-success mb-3" style="width:95%; margin:0 auto;">
                                    <div class="card-header">Upcoming Event</div>
                                    <div class="card-body">
                                        <h4 class="card-title">@Model.ElementAt(x).Title</h4>
                                        <img src="~/Content/Photos/event.png" style="width:100%; height:50%;" />
                                        <p class="card-text">@Model.ElementAt(x).partialContent</p>
                                        <a href='@Url.Action("single", "event",  new { id = Model.ElementAt(x).ID })'  role="button" class="btn btn-warning">More Information</a>
                                    </div>
                                </div>
                            </td>
                        }
                        x++;
                    }

                </tr>
            }
        </table>
    </section>

}

Events Management System Version 2.1/Views/Event/Single.cshtml
@model Events_Management_System_Version_2._1.Models.Event
@{
    ViewBag.Title = "Single";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="events full-width">
    <br />
    <div class="card text-white bg-info mb-3" style="max-height: 30%; max-width:50%; margin: 0 auto;">
        <div class="card-header">Event</div>
        <div class="card-body">
            <h4 class="card-title">@Model.Title</h4>
            <img src="~/Content/Photos/event.png" style="width:100%; height:50%;" />
            <p class="card-text">@Model.fullContent <br /> Event at @Model.Added_Date</p>

            @using (Html.BeginForm("Enroll", "Event"))
            {
                @Html.HiddenFor(n => n.ID)
                <button type="submit" class="btn btn-danger">Buy Ticket</button>
            }
        </div>
    </div>
</section>